/* tslint:disable */
/* eslint-disable */
/**
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const GpuType = {
    H100: 'H100',
    RTX_PRO_6000: 'RTX-PRO-6000',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type GpuType = typeof GpuType[keyof typeof GpuType];



