/* tslint:disable */
/* eslint-disable */
/**
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface KeyboardTypeRequest {
    /**
     * The text to type using the keyboard
     */
    'text': string;
    /**
     * Delay in milliseconds between keystrokes. Defaults to 0
     */
    'delay'?: number;
}

