/* tslint:disable */
/* eslint-disable */
/**
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProcessStatusResponse {
    /**
     * The name of the VNC process being checked
     */
    'processName': string;
    /**
     * Whether the specified VNC process is currently running
     */
    'running': boolean;
}

