# coding: utf-8

from __future__ import annotations

# flake8: noqa
"""
    Nightona

    Nightona AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: amaraaamka0404@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # import models into model package
    from nightona_api_client_async.models.account_provider import AccountProvider
    from nightona_api_client_async.models.admin_create_runner import AdminCreateRunner
    from nightona_api_client_async.models.admin_get_webhook_status200_response import AdminGetWebhookStatus200Response
    from nightona_api_client_async.models.announcement import Announcement
    from nightona_api_client_async.models.api_key_list import ApiKeyList
    from nightona_api_client_async.models.api_key_response import ApiKeyResponse
    from nightona_api_client_async.models.audit_log import AuditLog
    from nightona_api_client_async.models.build_info import BuildInfo
    from nightona_api_client_async.models.command import Command
    from nightona_api_client_async.models.completion_context import CompletionContext
    from nightona_api_client_async.models.completion_item import CompletionItem
    from nightona_api_client_async.models.completion_list import CompletionList
    from nightona_api_client_async.models.compressed_screenshot_response import CompressedScreenshotResponse
    from nightona_api_client_async.models.computer_use_start_response import ComputerUseStartResponse
    from nightona_api_client_async.models.computer_use_status_response import ComputerUseStatusResponse
    from nightona_api_client_async.models.computer_use_stop_response import ComputerUseStopResponse
    from nightona_api_client_async.models.create_api_key import CreateApiKey
    from nightona_api_client_async.models.create_build_info import CreateBuildInfo
    from nightona_api_client_async.models.create_docker_registry import CreateDockerRegistry
    from nightona_api_client_async.models.create_linked_account import CreateLinkedAccount
    from nightona_api_client_async.models.create_organization import CreateOrganization
    from nightona_api_client_async.models.create_organization_invitation import CreateOrganizationInvitation
    from nightona_api_client_async.models.create_organization_quota import CreateOrganizationQuota
    from nightona_api_client_async.models.create_organization_region_quota import CreateOrganizationRegionQuota
    from nightona_api_client_async.models.create_organization_role import CreateOrganizationRole
    from nightona_api_client_async.models.create_region import CreateRegion
    from nightona_api_client_async.models.create_region_response import CreateRegionResponse
    from nightona_api_client_async.models.create_runner import CreateRunner
    from nightona_api_client_async.models.create_runner_response import CreateRunnerResponse
    from nightona_api_client_async.models.create_sandbox import CreateSandbox
    from nightona_api_client_async.models.create_sandbox_snapshot import CreateSandboxSnapshot
    from nightona_api_client_async.models.create_session_request import CreateSessionRequest
    from nightona_api_client_async.models.create_snapshot import CreateSnapshot
    from nightona_api_client_async.models.create_user import CreateUser
    from nightona_api_client_async.models.create_volume import CreateVolume
    from nightona_api_client_async.models.nightona_configuration import NightonaConfiguration
    from nightona_api_client_async.models.display_info_response import DisplayInfoResponse
    from nightona_api_client_async.models.docker_registry import DockerRegistry
    from nightona_api_client_async.models.download_files import DownloadFiles
    from nightona_api_client_async.models.execute_request import ExecuteRequest
    from nightona_api_client_async.models.execute_response import ExecuteResponse
    from nightona_api_client_async.models.file_info import FileInfo
    from nightona_api_client_async.models.file_status import FileStatus
    from nightona_api_client_async.models.fork_sandbox import ForkSandbox
    from nightona_api_client_async.models.git_add_request import GitAddRequest
    from nightona_api_client_async.models.git_branch_request import GitBranchRequest
    from nightona_api_client_async.models.git_checkout_request import GitCheckoutRequest
    from nightona_api_client_async.models.git_clone_request import GitCloneRequest
    from nightona_api_client_async.models.git_commit_info import GitCommitInfo
    from nightona_api_client_async.models.git_commit_request import GitCommitRequest
    from nightona_api_client_async.models.git_commit_response import GitCommitResponse
    from nightona_api_client_async.models.git_delete_branch_request import GitDeleteBranchRequest
    from nightona_api_client_async.models.git_repo_request import GitRepoRequest
    from nightona_api_client_async.models.git_status import GitStatus
    from nightona_api_client_async.models.gpu_type import GpuType
    from nightona_api_client_async.models.health_controller_check200_response import HealthControllerCheck200Response
    from nightona_api_client_async.models.health_controller_check200_response_info_value import HealthControllerCheck200ResponseInfoValue
    from nightona_api_client_async.models.health_controller_check503_response import HealthControllerCheck503Response
    from nightona_api_client_async.models.job import Job
    from nightona_api_client_async.models.job_status import JobStatus
    from nightona_api_client_async.models.job_type import JobType
    from nightona_api_client_async.models.keyboard_hotkey_request import KeyboardHotkeyRequest
    from nightona_api_client_async.models.keyboard_press_request import KeyboardPressRequest
    from nightona_api_client_async.models.keyboard_type_request import KeyboardTypeRequest
    from nightona_api_client_async.models.list_branch_response import ListBranchResponse
    from nightona_api_client_async.models.list_sandboxes_response import ListSandboxesResponse
    from nightona_api_client_async.models.log_entry import LogEntry
    from nightona_api_client_async.models.lsp_completion_params import LspCompletionParams
    from nightona_api_client_async.models.lsp_document_request import LspDocumentRequest
    from nightona_api_client_async.models.lsp_location import LspLocation
    from nightona_api_client_async.models.lsp_server_request import LspServerRequest
    from nightona_api_client_async.models.lsp_symbol import LspSymbol
    from nightona_api_client_async.models.match import Match
    from nightona_api_client_async.models.metric_data_point import MetricDataPoint
    from nightona_api_client_async.models.metric_series import MetricSeries
    from nightona_api_client_async.models.metrics_response import MetricsResponse
    from nightona_api_client_async.models.mouse_click_request import MouseClickRequest
    from nightona_api_client_async.models.mouse_click_response import MouseClickResponse
    from nightona_api_client_async.models.mouse_drag_request import MouseDragRequest
    from nightona_api_client_async.models.mouse_drag_response import MouseDragResponse
    from nightona_api_client_async.models.mouse_move_request import MouseMoveRequest
    from nightona_api_client_async.models.mouse_move_response import MouseMoveResponse
    from nightona_api_client_async.models.mouse_position import MousePosition
    from nightona_api_client_async.models.mouse_scroll_request import MouseScrollRequest
    from nightona_api_client_async.models.mouse_scroll_response import MouseScrollResponse
    from nightona_api_client_async.models.oidc_config import OidcConfig
    from nightona_api_client_async.models.organization import Organization
    from nightona_api_client_async.models.organization_invitation import OrganizationInvitation
    from nightona_api_client_async.models.organization_role import OrganizationRole
    from nightona_api_client_async.models.organization_sandbox_default_limited_network_egress import OrganizationSandboxDefaultLimitedNetworkEgress
    from nightona_api_client_async.models.organization_suspension import OrganizationSuspension
    from nightona_api_client_async.models.organization_usage_overview import OrganizationUsageOverview
    from nightona_api_client_async.models.organization_user import OrganizationUser
    from nightona_api_client_async.models.otel_config import OtelConfig
    from nightona_api_client_async.models.paginated_audit_logs import PaginatedAuditLogs
    from nightona_api_client_async.models.paginated_jobs import PaginatedJobs
    from nightona_api_client_async.models.paginated_logs import PaginatedLogs
    from nightona_api_client_async.models.paginated_sandboxes_deprecated import PaginatedSandboxesDeprecated
    from nightona_api_client_async.models.paginated_snapshots import PaginatedSnapshots
    from nightona_api_client_async.models.paginated_traces import PaginatedTraces
    from nightona_api_client_async.models.poll_jobs_response import PollJobsResponse
    from nightona_api_client_async.models.port_preview_url import PortPreviewUrl
    from nightona_api_client_async.models.position import Position
    from nightona_api_client_async.models.posthog_config import PosthogConfig
    from nightona_api_client_async.models.process_errors_response import ProcessErrorsResponse
    from nightona_api_client_async.models.process_logs_response import ProcessLogsResponse
    from nightona_api_client_async.models.process_restart_response import ProcessRestartResponse
    from nightona_api_client_async.models.process_status_response import ProcessStatusResponse
    from nightona_api_client_async.models.project_dir_response import ProjectDirResponse
    from nightona_api_client_async.models.pty_create_request import PtyCreateRequest
    from nightona_api_client_async.models.pty_create_response import PtyCreateResponse
    from nightona_api_client_async.models.pty_list_response import PtyListResponse
    from nightona_api_client_async.models.pty_resize_request import PtyResizeRequest
    from nightona_api_client_async.models.pty_session_info import PtySessionInfo
    from nightona_api_client_async.models.range import Range
    from nightona_api_client_async.models.rate_limit_config import RateLimitConfig
    from nightona_api_client_async.models.rate_limit_entry import RateLimitEntry
    from nightona_api_client_async.models.regenerate_api_key_response import RegenerateApiKeyResponse
    from nightona_api_client_async.models.region import Region
    from nightona_api_client_async.models.region_quota import RegionQuota
    from nightona_api_client_async.models.region_screenshot_response import RegionScreenshotResponse
    from nightona_api_client_async.models.region_type import RegionType
    from nightona_api_client_async.models.region_usage_overview import RegionUsageOverview
    from nightona_api_client_async.models.registry_push_access_dto import RegistryPushAccessDto
    from nightona_api_client_async.models.replace_request import ReplaceRequest
    from nightona_api_client_async.models.replace_result import ReplaceResult
    from nightona_api_client_async.models.resize_sandbox import ResizeSandbox
    from nightona_api_client_async.models.runner import Runner
    from nightona_api_client_async.models.runner_class import RunnerClass
    from nightona_api_client_async.models.runner_full import RunnerFull
    from nightona_api_client_async.models.runner_health_metrics import RunnerHealthMetrics
    from nightona_api_client_async.models.runner_healthcheck import RunnerHealthcheck
    from nightona_api_client_async.models.runner_service_health import RunnerServiceHealth
    from nightona_api_client_async.models.runner_snapshot_dto import RunnerSnapshotDto
    from nightona_api_client_async.models.runner_state import RunnerState
    from nightona_api_client_async.models.sandbox import Sandbox
    from nightona_api_client_async.models.sandbox_class import SandboxClass
    from nightona_api_client_async.models.sandbox_desired_state import SandboxDesiredState
    from nightona_api_client_async.models.sandbox_labels import SandboxLabels
    from nightona_api_client_async.models.sandbox_list_item import SandboxListItem
    from nightona_api_client_async.models.sandbox_list_sort_direction import SandboxListSortDirection
    from nightona_api_client_async.models.sandbox_list_sort_field import SandboxListSortField
    from nightona_api_client_async.models.sandbox_state import SandboxState
    from nightona_api_client_async.models.sandbox_volume import SandboxVolume
    from nightona_api_client_async.models.screenshot_response import ScreenshotResponse
    from nightona_api_client_async.models.search_files_response import SearchFilesResponse
    from nightona_api_client_async.models.send_webhook_dto import SendWebhookDto
    from nightona_api_client_async.models.session import Session
    from nightona_api_client_async.models.session_execute_request import SessionExecuteRequest
    from nightona_api_client_async.models.session_execute_response import SessionExecuteResponse
    from nightona_api_client_async.models.set_snapshot_general_status_dto import SetSnapshotGeneralStatusDto
    from nightona_api_client_async.models.signed_port_preview_url import SignedPortPreviewUrl
    from nightona_api_client_async.models.snapshot_dto import SnapshotDto
    from nightona_api_client_async.models.snapshot_manager_credentials import SnapshotManagerCredentials
    from nightona_api_client_async.models.snapshot_state import SnapshotState
    from nightona_api_client_async.models.ssh_access_dto import SshAccessDto
    from nightona_api_client_async.models.ssh_access_validation_dto import SshAccessValidationDto
    from nightona_api_client_async.models.storage_access_dto import StorageAccessDto
    from nightona_api_client_async.models.toolbox_proxy_url import ToolboxProxyUrl
    from nightona_api_client_async.models.trace_span import TraceSpan
    from nightona_api_client_async.models.trace_summary import TraceSummary
    from nightona_api_client_async.models.update_docker_registry import UpdateDockerRegistry
    from nightona_api_client_async.models.update_job_status import UpdateJobStatus
    from nightona_api_client_async.models.update_organization_default_region import UpdateOrganizationDefaultRegion
    from nightona_api_client_async.models.update_organization_invitation import UpdateOrganizationInvitation
    from nightona_api_client_async.models.update_organization_member_access import UpdateOrganizationMemberAccess
    from nightona_api_client_async.models.update_organization_quota import UpdateOrganizationQuota
    from nightona_api_client_async.models.update_organization_region_quota import UpdateOrganizationRegionQuota
    from nightona_api_client_async.models.update_organization_role import UpdateOrganizationRole
    from nightona_api_client_async.models.update_region import UpdateRegion
    from nightona_api_client_async.models.update_sandbox_network_settings import UpdateSandboxNetworkSettings
    from nightona_api_client_async.models.update_sandbox_state_dto import UpdateSandboxStateDto
    from nightona_api_client_async.models.url import Url
    from nightona_api_client_async.models.user import User
    from nightona_api_client_async.models.user_home_dir_response import UserHomeDirResponse
    from nightona_api_client_async.models.user_public_key import UserPublicKey
    from nightona_api_client_async.models.volume_dto import VolumeDto
    from nightona_api_client_async.models.volume_state import VolumeState
    from nightona_api_client_async.models.webhook_app_portal_access import WebhookAppPortalAccess
    from nightona_api_client_async.models.webhook_event import WebhookEvent
    from nightona_api_client_async.models.webhook_initialization_status import WebhookInitializationStatus
    from nightona_api_client_async.models.windows_response import WindowsResponse
    from nightona_api_client_async.models.work_dir_response import WorkDirResponse

_DYNAMIC_IMPORTS: dict[str, str] = {
    "AccountProvider": "nightona_api_client_async.models.account_provider",
    "AdminCreateRunner": "nightona_api_client_async.models.admin_create_runner",
    "AdminGetWebhookStatus200Response": "nightona_api_client_async.models.admin_get_webhook_status200_response",
    "Announcement": "nightona_api_client_async.models.announcement",
    "ApiKeyList": "nightona_api_client_async.models.api_key_list",
    "ApiKeyResponse": "nightona_api_client_async.models.api_key_response",
    "AuditLog": "nightona_api_client_async.models.audit_log",
    "BuildInfo": "nightona_api_client_async.models.build_info",
    "Command": "nightona_api_client_async.models.command",
    "CompletionContext": "nightona_api_client_async.models.completion_context",
    "CompletionItem": "nightona_api_client_async.models.completion_item",
    "CompletionList": "nightona_api_client_async.models.completion_list",
    "CompressedScreenshotResponse": "nightona_api_client_async.models.compressed_screenshot_response",
    "ComputerUseStartResponse": "nightona_api_client_async.models.computer_use_start_response",
    "ComputerUseStatusResponse": "nightona_api_client_async.models.computer_use_status_response",
    "ComputerUseStopResponse": "nightona_api_client_async.models.computer_use_stop_response",
    "CreateApiKey": "nightona_api_client_async.models.create_api_key",
    "CreateBuildInfo": "nightona_api_client_async.models.create_build_info",
    "CreateDockerRegistry": "nightona_api_client_async.models.create_docker_registry",
    "CreateLinkedAccount": "nightona_api_client_async.models.create_linked_account",
    "CreateOrganization": "nightona_api_client_async.models.create_organization",
    "CreateOrganizationInvitation": "nightona_api_client_async.models.create_organization_invitation",
    "CreateOrganizationQuota": "nightona_api_client_async.models.create_organization_quota",
    "CreateOrganizationRegionQuota": "nightona_api_client_async.models.create_organization_region_quota",
    "CreateOrganizationRole": "nightona_api_client_async.models.create_organization_role",
    "CreateRegion": "nightona_api_client_async.models.create_region",
    "CreateRegionResponse": "nightona_api_client_async.models.create_region_response",
    "CreateRunner": "nightona_api_client_async.models.create_runner",
    "CreateRunnerResponse": "nightona_api_client_async.models.create_runner_response",
    "CreateSandbox": "nightona_api_client_async.models.create_sandbox",
    "CreateSandboxSnapshot": "nightona_api_client_async.models.create_sandbox_snapshot",
    "CreateSessionRequest": "nightona_api_client_async.models.create_session_request",
    "CreateSnapshot": "nightona_api_client_async.models.create_snapshot",
    "CreateUser": "nightona_api_client_async.models.create_user",
    "CreateVolume": "nightona_api_client_async.models.create_volume",
    "NightonaConfiguration": "nightona_api_client_async.models.nightona_configuration",
    "DisplayInfoResponse": "nightona_api_client_async.models.display_info_response",
    "DockerRegistry": "nightona_api_client_async.models.docker_registry",
    "DownloadFiles": "nightona_api_client_async.models.download_files",
    "ExecuteRequest": "nightona_api_client_async.models.execute_request",
    "ExecuteResponse": "nightona_api_client_async.models.execute_response",
    "FileInfo": "nightona_api_client_async.models.file_info",
    "FileStatus": "nightona_api_client_async.models.file_status",
    "ForkSandbox": "nightona_api_client_async.models.fork_sandbox",
    "GitAddRequest": "nightona_api_client_async.models.git_add_request",
    "GitBranchRequest": "nightona_api_client_async.models.git_branch_request",
    "GitCheckoutRequest": "nightona_api_client_async.models.git_checkout_request",
    "GitCloneRequest": "nightona_api_client_async.models.git_clone_request",
    "GitCommitInfo": "nightona_api_client_async.models.git_commit_info",
    "GitCommitRequest": "nightona_api_client_async.models.git_commit_request",
    "GitCommitResponse": "nightona_api_client_async.models.git_commit_response",
    "GitDeleteBranchRequest": "nightona_api_client_async.models.git_delete_branch_request",
    "GitRepoRequest": "nightona_api_client_async.models.git_repo_request",
    "GitStatus": "nightona_api_client_async.models.git_status",
    "GpuType": "nightona_api_client_async.models.gpu_type",
    "HealthControllerCheck200Response": "nightona_api_client_async.models.health_controller_check200_response",
    "HealthControllerCheck200ResponseInfoValue": "nightona_api_client_async.models.health_controller_check200_response_info_value",
    "HealthControllerCheck503Response": "nightona_api_client_async.models.health_controller_check503_response",
    "Job": "nightona_api_client_async.models.job",
    "JobStatus": "nightona_api_client_async.models.job_status",
    "JobType": "nightona_api_client_async.models.job_type",
    "KeyboardHotkeyRequest": "nightona_api_client_async.models.keyboard_hotkey_request",
    "KeyboardPressRequest": "nightona_api_client_async.models.keyboard_press_request",
    "KeyboardTypeRequest": "nightona_api_client_async.models.keyboard_type_request",
    "ListBranchResponse": "nightona_api_client_async.models.list_branch_response",
    "ListSandboxesResponse": "nightona_api_client_async.models.list_sandboxes_response",
    "LogEntry": "nightona_api_client_async.models.log_entry",
    "LspCompletionParams": "nightona_api_client_async.models.lsp_completion_params",
    "LspDocumentRequest": "nightona_api_client_async.models.lsp_document_request",
    "LspLocation": "nightona_api_client_async.models.lsp_location",
    "LspServerRequest": "nightona_api_client_async.models.lsp_server_request",
    "LspSymbol": "nightona_api_client_async.models.lsp_symbol",
    "Match": "nightona_api_client_async.models.match",
    "MetricDataPoint": "nightona_api_client_async.models.metric_data_point",
    "MetricSeries": "nightona_api_client_async.models.metric_series",
    "MetricsResponse": "nightona_api_client_async.models.metrics_response",
    "MouseClickRequest": "nightona_api_client_async.models.mouse_click_request",
    "MouseClickResponse": "nightona_api_client_async.models.mouse_click_response",
    "MouseDragRequest": "nightona_api_client_async.models.mouse_drag_request",
    "MouseDragResponse": "nightona_api_client_async.models.mouse_drag_response",
    "MouseMoveRequest": "nightona_api_client_async.models.mouse_move_request",
    "MouseMoveResponse": "nightona_api_client_async.models.mouse_move_response",
    "MousePosition": "nightona_api_client_async.models.mouse_position",
    "MouseScrollRequest": "nightona_api_client_async.models.mouse_scroll_request",
    "MouseScrollResponse": "nightona_api_client_async.models.mouse_scroll_response",
    "OidcConfig": "nightona_api_client_async.models.oidc_config",
    "Organization": "nightona_api_client_async.models.organization",
    "OrganizationInvitation": "nightona_api_client_async.models.organization_invitation",
    "OrganizationRole": "nightona_api_client_async.models.organization_role",
    "OrganizationSandboxDefaultLimitedNetworkEgress": "nightona_api_client_async.models.organization_sandbox_default_limited_network_egress",
    "OrganizationSuspension": "nightona_api_client_async.models.organization_suspension",
    "OrganizationUsageOverview": "nightona_api_client_async.models.organization_usage_overview",
    "OrganizationUser": "nightona_api_client_async.models.organization_user",
    "OtelConfig": "nightona_api_client_async.models.otel_config",
    "PaginatedAuditLogs": "nightona_api_client_async.models.paginated_audit_logs",
    "PaginatedJobs": "nightona_api_client_async.models.paginated_jobs",
    "PaginatedLogs": "nightona_api_client_async.models.paginated_logs",
    "PaginatedSandboxesDeprecated": "nightona_api_client_async.models.paginated_sandboxes_deprecated",
    "PaginatedSnapshots": "nightona_api_client_async.models.paginated_snapshots",
    "PaginatedTraces": "nightona_api_client_async.models.paginated_traces",
    "PollJobsResponse": "nightona_api_client_async.models.poll_jobs_response",
    "PortPreviewUrl": "nightona_api_client_async.models.port_preview_url",
    "Position": "nightona_api_client_async.models.position",
    "PosthogConfig": "nightona_api_client_async.models.posthog_config",
    "ProcessErrorsResponse": "nightona_api_client_async.models.process_errors_response",
    "ProcessLogsResponse": "nightona_api_client_async.models.process_logs_response",
    "ProcessRestartResponse": "nightona_api_client_async.models.process_restart_response",
    "ProcessStatusResponse": "nightona_api_client_async.models.process_status_response",
    "ProjectDirResponse": "nightona_api_client_async.models.project_dir_response",
    "PtyCreateRequest": "nightona_api_client_async.models.pty_create_request",
    "PtyCreateResponse": "nightona_api_client_async.models.pty_create_response",
    "PtyListResponse": "nightona_api_client_async.models.pty_list_response",
    "PtyResizeRequest": "nightona_api_client_async.models.pty_resize_request",
    "PtySessionInfo": "nightona_api_client_async.models.pty_session_info",
    "Range": "nightona_api_client_async.models.range",
    "RateLimitConfig": "nightona_api_client_async.models.rate_limit_config",
    "RateLimitEntry": "nightona_api_client_async.models.rate_limit_entry",
    "RegenerateApiKeyResponse": "nightona_api_client_async.models.regenerate_api_key_response",
    "Region": "nightona_api_client_async.models.region",
    "RegionQuota": "nightona_api_client_async.models.region_quota",
    "RegionScreenshotResponse": "nightona_api_client_async.models.region_screenshot_response",
    "RegionType": "nightona_api_client_async.models.region_type",
    "RegionUsageOverview": "nightona_api_client_async.models.region_usage_overview",
    "RegistryPushAccessDto": "nightona_api_client_async.models.registry_push_access_dto",
    "ReplaceRequest": "nightona_api_client_async.models.replace_request",
    "ReplaceResult": "nightona_api_client_async.models.replace_result",
    "ResizeSandbox": "nightona_api_client_async.models.resize_sandbox",
    "Runner": "nightona_api_client_async.models.runner",
    "RunnerClass": "nightona_api_client_async.models.runner_class",
    "RunnerFull": "nightona_api_client_async.models.runner_full",
    "RunnerHealthMetrics": "nightona_api_client_async.models.runner_health_metrics",
    "RunnerHealthcheck": "nightona_api_client_async.models.runner_healthcheck",
    "RunnerServiceHealth": "nightona_api_client_async.models.runner_service_health",
    "RunnerSnapshotDto": "nightona_api_client_async.models.runner_snapshot_dto",
    "RunnerState": "nightona_api_client_async.models.runner_state",
    "Sandbox": "nightona_api_client_async.models.sandbox",
    "SandboxClass": "nightona_api_client_async.models.sandbox_class",
    "SandboxDesiredState": "nightona_api_client_async.models.sandbox_desired_state",
    "SandboxLabels": "nightona_api_client_async.models.sandbox_labels",
    "SandboxListItem": "nightona_api_client_async.models.sandbox_list_item",
    "SandboxListSortDirection": "nightona_api_client_async.models.sandbox_list_sort_direction",
    "SandboxListSortField": "nightona_api_client_async.models.sandbox_list_sort_field",
    "SandboxState": "nightona_api_client_async.models.sandbox_state",
    "SandboxVolume": "nightona_api_client_async.models.sandbox_volume",
    "ScreenshotResponse": "nightona_api_client_async.models.screenshot_response",
    "SearchFilesResponse": "nightona_api_client_async.models.search_files_response",
    "SendWebhookDto": "nightona_api_client_async.models.send_webhook_dto",
    "Session": "nightona_api_client_async.models.session",
    "SessionExecuteRequest": "nightona_api_client_async.models.session_execute_request",
    "SessionExecuteResponse": "nightona_api_client_async.models.session_execute_response",
    "SetSnapshotGeneralStatusDto": "nightona_api_client_async.models.set_snapshot_general_status_dto",
    "SignedPortPreviewUrl": "nightona_api_client_async.models.signed_port_preview_url",
    "SnapshotDto": "nightona_api_client_async.models.snapshot_dto",
    "SnapshotManagerCredentials": "nightona_api_client_async.models.snapshot_manager_credentials",
    "SnapshotState": "nightona_api_client_async.models.snapshot_state",
    "SshAccessDto": "nightona_api_client_async.models.ssh_access_dto",
    "SshAccessValidationDto": "nightona_api_client_async.models.ssh_access_validation_dto",
    "StorageAccessDto": "nightona_api_client_async.models.storage_access_dto",
    "ToolboxProxyUrl": "nightona_api_client_async.models.toolbox_proxy_url",
    "TraceSpan": "nightona_api_client_async.models.trace_span",
    "TraceSummary": "nightona_api_client_async.models.trace_summary",
    "UpdateDockerRegistry": "nightona_api_client_async.models.update_docker_registry",
    "UpdateJobStatus": "nightona_api_client_async.models.update_job_status",
    "UpdateOrganizationDefaultRegion": "nightona_api_client_async.models.update_organization_default_region",
    "UpdateOrganizationInvitation": "nightona_api_client_async.models.update_organization_invitation",
    "UpdateOrganizationMemberAccess": "nightona_api_client_async.models.update_organization_member_access",
    "UpdateOrganizationQuota": "nightona_api_client_async.models.update_organization_quota",
    "UpdateOrganizationRegionQuota": "nightona_api_client_async.models.update_organization_region_quota",
    "UpdateOrganizationRole": "nightona_api_client_async.models.update_organization_role",
    "UpdateRegion": "nightona_api_client_async.models.update_region",
    "UpdateSandboxNetworkSettings": "nightona_api_client_async.models.update_sandbox_network_settings",
    "UpdateSandboxStateDto": "nightona_api_client_async.models.update_sandbox_state_dto",
    "Url": "nightona_api_client_async.models.url",
    "User": "nightona_api_client_async.models.user",
    "UserHomeDirResponse": "nightona_api_client_async.models.user_home_dir_response",
    "UserPublicKey": "nightona_api_client_async.models.user_public_key",
    "VolumeDto": "nightona_api_client_async.models.volume_dto",
    "VolumeState": "nightona_api_client_async.models.volume_state",
    "WebhookAppPortalAccess": "nightona_api_client_async.models.webhook_app_portal_access",
    "WebhookEvent": "nightona_api_client_async.models.webhook_event",
    "WebhookInitializationStatus": "nightona_api_client_async.models.webhook_initialization_status",
    "WindowsResponse": "nightona_api_client_async.models.windows_response",
    "WorkDirResponse": "nightona_api_client_async.models.work_dir_response",
}


def __getattr__(attr_name: str) -> object:
    module_path = _DYNAMIC_IMPORTS.get(attr_name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {attr_name!r}")
    mod = importlib.import_module(module_path)
    value = getattr(mod, attr_name)
    globals()[attr_name] = value
    return value


def __dir__() -> list[str]:
    return list(_DYNAMIC_IMPORTS.keys())
