/*
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightona.api.client.api;

import io.nightona.api.client.ApiException;
import io.nightona.api.client.model.ApiKeyList;
import io.nightona.api.client.model.ApiKeyResponse;
import io.nightona.api.client.model.CreateApiKey;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiKeysApi
 */
@Disabled
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    /**
     * Create API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createApiKeyTest() throws ApiException {
        CreateApiKey createApiKey = null;
        String xNightonaOrganizationID = null;
        ApiKeyResponse response = api.createApiKey(createApiKey, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Delete API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteApiKeyTest() throws ApiException {
        String name = null;
        String xNightonaOrganizationID = null;
        api.deleteApiKey(name, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Delete API key for user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteApiKeyForUserTest() throws ApiException {
        String userId = null;
        String name = null;
        String xNightonaOrganizationID = null;
        api.deleteApiKeyForUser(userId, name, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApiKeyTest() throws ApiException {
        String name = null;
        String xNightonaOrganizationID = null;
        ApiKeyList response = api.getApiKey(name, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get current API key&#39;s details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCurrentApiKeyTest() throws ApiException {
        String xNightonaOrganizationID = null;
        ApiKeyList response = api.getCurrentApiKey(xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List API keys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listApiKeysTest() throws ApiException {
        String xNightonaOrganizationID = null;
        List<ApiKeyList> response = api.listApiKeys(xNightonaOrganizationID);
        // TODO: test validations
    }

}
