/*
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightona.api.client.api;

import io.nightona.api.client.ApiException;
import io.nightona.api.client.model.CreateDockerRegistry;
import io.nightona.api.client.model.DockerRegistry;
import io.nightona.api.client.model.RegistryPushAccessDto;
import io.nightona.api.client.model.UpdateDockerRegistry;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DockerRegistryApi
 */
@Disabled
public class DockerRegistryApiTest {

    private final DockerRegistryApi api = new DockerRegistryApi();

    /**
     * Create registry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRegistryTest() throws ApiException {
        CreateDockerRegistry createDockerRegistry = null;
        String xNightonaOrganizationID = null;
        DockerRegistry response = api.createRegistry(createDockerRegistry, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Delete registry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRegistryTest() throws ApiException {
        String id = null;
        String xNightonaOrganizationID = null;
        api.deleteRegistry(id, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get registry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRegistryTest() throws ApiException {
        String id = null;
        String xNightonaOrganizationID = null;
        DockerRegistry response = api.getRegistry(id, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get temporary registry access for pushing snapshots
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTransientPushAccessTest() throws ApiException {
        String xNightonaOrganizationID = null;
        String regionId = null;
        RegistryPushAccessDto response = api.getTransientPushAccess(xNightonaOrganizationID, regionId);
        // TODO: test validations
    }

    /**
     * List registries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listRegistriesTest() throws ApiException {
        String xNightonaOrganizationID = null;
        List<DockerRegistry> response = api.listRegistries(xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Update registry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRegistryTest() throws ApiException {
        String id = null;
        UpdateDockerRegistry updateDockerRegistry = null;
        String xNightonaOrganizationID = null;
        DockerRegistry response = api.updateRegistry(id, updateDockerRegistry, xNightonaOrganizationID);
        // TODO: test validations
    }

}
