/*
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightona.api.client.api;

import io.nightona.api.client.ApiException;
import java.math.BigDecimal;
import io.nightona.api.client.model.Command;
import io.nightona.api.client.model.CompletionList;
import io.nightona.api.client.model.CompressedScreenshotResponse;
import io.nightona.api.client.model.ComputerUseStartResponse;
import io.nightona.api.client.model.ComputerUseStatusResponse;
import io.nightona.api.client.model.ComputerUseStopResponse;
import io.nightona.api.client.model.CreateSessionRequest;
import io.nightona.api.client.model.DisplayInfoResponse;
import io.nightona.api.client.model.DownloadFiles;
import io.nightona.api.client.model.ExecuteRequest;
import io.nightona.api.client.model.ExecuteResponse;
import java.io.File;
import io.nightona.api.client.model.FileInfo;
import io.nightona.api.client.model.GitAddRequest;
import io.nightona.api.client.model.GitBranchRequest;
import io.nightona.api.client.model.GitCheckoutRequest;
import io.nightona.api.client.model.GitCloneRequest;
import io.nightona.api.client.model.GitCommitInfo;
import io.nightona.api.client.model.GitCommitRequest;
import io.nightona.api.client.model.GitCommitResponse;
import io.nightona.api.client.model.GitDeleteBranchRequest;
import io.nightona.api.client.model.GitRepoRequest;
import io.nightona.api.client.model.GitStatus;
import io.nightona.api.client.model.KeyboardHotkeyRequest;
import io.nightona.api.client.model.KeyboardPressRequest;
import io.nightona.api.client.model.KeyboardTypeRequest;
import io.nightona.api.client.model.ListBranchResponse;
import io.nightona.api.client.model.LspCompletionParams;
import io.nightona.api.client.model.LspDocumentRequest;
import io.nightona.api.client.model.LspServerRequest;
import io.nightona.api.client.model.LspSymbol;
import io.nightona.api.client.model.Match;
import io.nightona.api.client.model.MouseClickRequest;
import io.nightona.api.client.model.MouseClickResponse;
import io.nightona.api.client.model.MouseDragRequest;
import io.nightona.api.client.model.MouseDragResponse;
import io.nightona.api.client.model.MouseMoveRequest;
import io.nightona.api.client.model.MouseMoveResponse;
import io.nightona.api.client.model.MousePosition;
import io.nightona.api.client.model.MouseScrollRequest;
import io.nightona.api.client.model.MouseScrollResponse;
import io.nightona.api.client.model.ProcessErrorsResponse;
import io.nightona.api.client.model.ProcessLogsResponse;
import io.nightona.api.client.model.ProcessRestartResponse;
import io.nightona.api.client.model.ProcessStatusResponse;
import io.nightona.api.client.model.ProjectDirResponse;
import io.nightona.api.client.model.PtyCreateRequest;
import io.nightona.api.client.model.PtyCreateResponse;
import io.nightona.api.client.model.PtyListResponse;
import io.nightona.api.client.model.PtyResizeRequest;
import io.nightona.api.client.model.PtySessionInfo;
import io.nightona.api.client.model.RegionScreenshotResponse;
import io.nightona.api.client.model.ReplaceRequest;
import io.nightona.api.client.model.ReplaceResult;
import io.nightona.api.client.model.ScreenshotResponse;
import io.nightona.api.client.model.SearchFilesResponse;
import io.nightona.api.client.model.Session;
import io.nightona.api.client.model.SessionExecuteRequest;
import io.nightona.api.client.model.SessionExecuteResponse;
import io.nightona.api.client.model.UserHomeDirResponse;
import io.nightona.api.client.model.WindowsResponse;
import io.nightona.api.client.model.WorkDirResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ToolboxApi
 */
@Disabled
public class ToolboxApiTest {

    private final ToolboxApi api = new ToolboxApi();

    /**
     * [DEPRECATED] Click mouse
     *
     * Click mouse at specified coordinates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void clickMouseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        MouseClickRequest mouseClickRequest = null;
        String xNightonaOrganizationID = null;
        MouseClickResponse response = api.clickMouseDeprecated(sandboxId, mouseClickRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Create folder
     *
     * Create folder inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createFolderDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String mode = null;
        String xNightonaOrganizationID = null;
        api.createFolderDeprecated(sandboxId, path, mode, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Create PTY session
     *
     * Create a new PTY session in the sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPTYSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        PtyCreateRequest ptyCreateRequest = null;
        String xNightonaOrganizationID = null;
        PtyCreateResponse response = api.createPTYSessionDeprecated(sandboxId, ptyCreateRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Create session
     *
     * Create a new session in the sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        CreateSessionRequest createSessionRequest = null;
        String xNightonaOrganizationID = null;
        api.createSessionDeprecated(sandboxId, createSessionRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Delete file
     *
     * Delete file inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteFileDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        Boolean recursive = null;
        api.deleteFileDeprecated(sandboxId, path, xNightonaOrganizationID, recursive);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Delete PTY session
     *
     * Delete a PTY session and terminate the associated process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePTYSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        String xNightonaOrganizationID = null;
        api.deletePTYSessionDeprecated(sandboxId, sessionId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Delete session
     *
     * Delete a specific session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        String xNightonaOrganizationID = null;
        api.deleteSessionDeprecated(sandboxId, sessionId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Download file
     *
     * Download file from sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadFileDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        File response = api.downloadFileDeprecated(sandboxId, path, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Download multiple files
     *
     * Streams back a multipart/form-data bundle of the requested paths
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        DownloadFiles downloadFiles = null;
        String xNightonaOrganizationID = null;
        File response = api.downloadFilesDeprecated(sandboxId, downloadFiles, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Drag mouse
     *
     * Drag mouse from start to end coordinates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dragMouseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        MouseDragRequest mouseDragRequest = null;
        String xNightonaOrganizationID = null;
        MouseDragResponse response = api.dragMouseDeprecated(sandboxId, mouseDragRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Execute command
     *
     * Execute command synchronously inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void executeCommandDeprecatedTest() throws ApiException {
        String sandboxId = null;
        ExecuteRequest executeRequest = null;
        String xNightonaOrganizationID = null;
        ExecuteResponse response = api.executeCommandDeprecated(sandboxId, executeRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Execute command in session
     *
     * Execute a command in a specific session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void executeSessionCommandDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        SessionExecuteRequest sessionExecuteRequest = null;
        String xNightonaOrganizationID = null;
        SessionExecuteResponse response = api.executeSessionCommandDeprecated(sandboxId, sessionId, sessionExecuteRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Search for text/pattern in files
     *
     * Search for text/pattern inside sandbox files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findInFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String pattern = null;
        String xNightonaOrganizationID = null;
        List<Match> response = api.findInFilesDeprecated(sandboxId, path, pattern, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get computer use status
     *
     * Get status of all VNC desktop processes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getComputerUseStatusDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ComputerUseStatusResponse response = api.getComputerUseStatusDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get display info
     *
     * Get information about displays
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDisplayInfoDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        DisplayInfoResponse response = api.getDisplayInfoDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get file info
     *
     * Get file info inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFileInfoDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        FileInfo response = api.getFileInfoDeprecated(sandboxId, path, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get mouse position
     *
     * Get current mouse cursor position
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMousePositionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        MousePosition response = api.getMousePositionDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get PTY session
     *
     * Get PTY session information by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPTYSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        String xNightonaOrganizationID = null;
        PtySessionInfo response = api.getPTYSessionDeprecated(sandboxId, sessionId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get process errors
     *
     * Get error logs for a specific VNC process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProcessErrorsDeprecatedTest() throws ApiException {
        String processName = null;
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ProcessErrorsResponse response = api.getProcessErrorsDeprecated(processName, sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get process logs
     *
     * Get logs for a specific VNC process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProcessLogsDeprecatedTest() throws ApiException {
        String processName = null;
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ProcessLogsResponse response = api.getProcessLogsDeprecated(processName, sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get process status
     *
     * Get status of a specific VNC process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProcessStatusDeprecatedTest() throws ApiException {
        String processName = null;
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ProcessStatusResponse response = api.getProcessStatusDeprecated(processName, sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get sandbox project dir
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectDirDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ProjectDirResponse response = api.getProjectDirDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get session command
     *
     * Get session command by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSessionCommandDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        String commandId = null;
        String xNightonaOrganizationID = null;
        Command response = api.getSessionCommandDeprecated(sandboxId, sessionId, commandId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get command logs
     *
     * Get logs for a specific command in a session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSessionCommandLogsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        String commandId = null;
        String xNightonaOrganizationID = null;
        Boolean follow = null;
        String response = api.getSessionCommandLogsDeprecated(sandboxId, sessionId, commandId, xNightonaOrganizationID, follow);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get session
     *
     * Get session by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        String xNightonaOrganizationID = null;
        Session response = api.getSessionDeprecated(sandboxId, sessionId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get sandbox user home dir
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserHomeDirDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        UserHomeDirResponse response = api.getUserHomeDirDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get windows
     *
     * Get list of open windows
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWindowsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        WindowsResponse response = api.getWindowsDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get sandbox work-dir
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWorkDirDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        WorkDirResponse response = api.getWorkDirDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Add files
     *
     * Add files to git commit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitAddFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitAddRequest gitAddRequest = null;
        String xNightonaOrganizationID = null;
        api.gitAddFilesDeprecated(sandboxId, gitAddRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Checkout branch
     *
     * Checkout branch or commit in git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitCheckoutBranchDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitCheckoutRequest gitCheckoutRequest = null;
        String xNightonaOrganizationID = null;
        api.gitCheckoutBranchDeprecated(sandboxId, gitCheckoutRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Clone repository
     *
     * Clone git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitCloneRepositoryDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitCloneRequest gitCloneRequest = null;
        String xNightonaOrganizationID = null;
        api.gitCloneRepositoryDeprecated(sandboxId, gitCloneRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Commit changes
     *
     * Commit changes to git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitCommitChangesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitCommitRequest gitCommitRequest = null;
        String xNightonaOrganizationID = null;
        GitCommitResponse response = api.gitCommitChangesDeprecated(sandboxId, gitCommitRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Create branch
     *
     * Create branch on git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitCreateBranchDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitBranchRequest gitBranchRequest = null;
        String xNightonaOrganizationID = null;
        api.gitCreateBranchDeprecated(sandboxId, gitBranchRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Delete branch
     *
     * Delete branch on git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitDeleteBranchDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitDeleteBranchRequest gitDeleteBranchRequest = null;
        String xNightonaOrganizationID = null;
        api.gitDeleteBranchDeprecated(sandboxId, gitDeleteBranchRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get commit history
     *
     * Get commit history from git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitGetHistoryDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        List<GitCommitInfo> response = api.gitGetHistoryDeprecated(sandboxId, path, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get git status
     *
     * Get status from git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitGetStatusDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        GitStatus response = api.gitGetStatusDeprecated(sandboxId, path, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get branch list
     *
     * Get branch list from git repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitListBranchesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        ListBranchResponse response = api.gitListBranchesDeprecated(sandboxId, path, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Pull changes
     *
     * Pull changes from remote
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitPullChangesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitRepoRequest gitRepoRequest = null;
        String xNightonaOrganizationID = null;
        api.gitPullChangesDeprecated(sandboxId, gitRepoRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Push changes
     *
     * Push changes to remote
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void gitPushChangesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        GitRepoRequest gitRepoRequest = null;
        String xNightonaOrganizationID = null;
        api.gitPushChangesDeprecated(sandboxId, gitRepoRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] List files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        String path = null;
        List<FileInfo> response = api.listFilesDeprecated(sandboxId, xNightonaOrganizationID, path);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] List PTY sessions
     *
     * List all active PTY sessions in the sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPTYSessionsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        PtyListResponse response = api.listPTYSessionsDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] List sessions
     *
     * List all active sessions in the sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSessionsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        List<Session> response = api.listSessionsDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Get Lsp Completions
     *
     * The Completion request is sent from the client to the server to compute completion items at a given cursor position.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspCompletionsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        LspCompletionParams lspCompletionParams = null;
        String xNightonaOrganizationID = null;
        CompletionList response = api.lspCompletionsDeprecated(sandboxId, lspCompletionParams, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Call Lsp DidClose
     *
     * The document close notification is sent from the client to the server when the document got closed in the client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspDidCloseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        LspDocumentRequest lspDocumentRequest = null;
        String xNightonaOrganizationID = null;
        api.lspDidCloseDeprecated(sandboxId, lspDocumentRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Call Lsp DidOpen
     *
     * The document open notification is sent from the client to the server to signal newly opened text documents.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspDidOpenDeprecatedTest() throws ApiException {
        String sandboxId = null;
        LspDocumentRequest lspDocumentRequest = null;
        String xNightonaOrganizationID = null;
        api.lspDidOpenDeprecated(sandboxId, lspDocumentRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Call Lsp DocumentSymbols
     *
     * The document symbol request is sent from the client to the server.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspDocumentSymbolsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String languageId = null;
        String pathToProject = null;
        String uri = null;
        String xNightonaOrganizationID = null;
        List<LspSymbol> response = api.lspDocumentSymbolsDeprecated(sandboxId, languageId, pathToProject, uri, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Start Lsp server
     *
     * Start Lsp server process inside sandbox project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspStartDeprecatedTest() throws ApiException {
        String sandboxId = null;
        LspServerRequest lspServerRequest = null;
        String xNightonaOrganizationID = null;
        api.lspStartDeprecated(sandboxId, lspServerRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Stop Lsp server
     *
     * Stop Lsp server process inside sandbox project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspStopDeprecatedTest() throws ApiException {
        String sandboxId = null;
        LspServerRequest lspServerRequest = null;
        String xNightonaOrganizationID = null;
        api.lspStopDeprecated(sandboxId, lspServerRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Call Lsp WorkspaceSymbols
     *
     * The workspace symbol request is sent from the client to the server to list project-wide symbols matching the query string.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lspWorkspaceSymbolsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String languageId = null;
        String pathToProject = null;
        String query = null;
        String xNightonaOrganizationID = null;
        List<LspSymbol> response = api.lspWorkspaceSymbolsDeprecated(sandboxId, languageId, pathToProject, query, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Move file
     *
     * Move file inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void moveFileDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String source = null;
        String destination = null;
        String xNightonaOrganizationID = null;
        api.moveFileDeprecated(sandboxId, source, destination, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Move mouse
     *
     * Move mouse cursor to specified coordinates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void moveMouseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        MouseMoveRequest mouseMoveRequest = null;
        String xNightonaOrganizationID = null;
        MouseMoveResponse response = api.moveMouseDeprecated(sandboxId, mouseMoveRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Press hotkey
     *
     * Press a hotkey combination
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pressHotkeyDeprecatedTest() throws ApiException {
        String sandboxId = null;
        KeyboardHotkeyRequest keyboardHotkeyRequest = null;
        String xNightonaOrganizationID = null;
        api.pressHotkeyDeprecated(sandboxId, keyboardHotkeyRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Press key
     *
     * Press a key with optional modifiers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pressKeyDeprecatedTest() throws ApiException {
        String sandboxId = null;
        KeyboardPressRequest keyboardPressRequest = null;
        String xNightonaOrganizationID = null;
        api.pressKeyDeprecated(sandboxId, keyboardPressRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Replace in files
     *
     * Replace text/pattern in multiple files inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void replaceInFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        ReplaceRequest replaceRequest = null;
        String xNightonaOrganizationID = null;
        List<ReplaceResult> response = api.replaceInFilesDeprecated(sandboxId, replaceRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Resize PTY session
     *
     * Resize a PTY session
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resizePTYSessionDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String sessionId = null;
        PtyResizeRequest ptyResizeRequest = null;
        String xNightonaOrganizationID = null;
        PtySessionInfo response = api.resizePTYSessionDeprecated(sandboxId, sessionId, ptyResizeRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Restart process
     *
     * Restart a specific VNC process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void restartProcessDeprecatedTest() throws ApiException {
        String processName = null;
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ProcessRestartResponse response = api.restartProcessDeprecated(processName, sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Scroll mouse
     *
     * Scroll mouse at specified coordinates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scrollMouseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        MouseScrollRequest mouseScrollRequest = null;
        String xNightonaOrganizationID = null;
        MouseScrollResponse response = api.scrollMouseDeprecated(sandboxId, mouseScrollRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Search files
     *
     * Search for files inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String pattern = null;
        String xNightonaOrganizationID = null;
        SearchFilesResponse response = api.searchFilesDeprecated(sandboxId, path, pattern, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Set file permissions
     *
     * Set file owner/group/permissions inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setFilePermissionsDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        String owner = null;
        String group = null;
        String mode = null;
        api.setFilePermissionsDeprecated(sandboxId, path, xNightonaOrganizationID, owner, group, mode);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Start computer use processes
     *
     * Start all VNC desktop processes (Xvfb, xfce4, x11vnc, novnc)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void startComputerUseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ComputerUseStartResponse response = api.startComputerUseDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Stop computer use processes
     *
     * Stop all VNC desktop processes (Xvfb, xfce4, x11vnc, novnc)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void stopComputerUseDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        ComputerUseStopResponse response = api.stopComputerUseDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Take compressed region screenshot
     *
     * Take a compressed screenshot of a specific region
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void takeCompressedRegionScreenshotDeprecatedTest() throws ApiException {
        String sandboxId = null;
        BigDecimal height = null;
        BigDecimal width = null;
        BigDecimal y = null;
        BigDecimal x = null;
        String xNightonaOrganizationID = null;
        BigDecimal scale = null;
        BigDecimal quality = null;
        String format = null;
        Boolean showCursor = null;
        CompressedScreenshotResponse response = api.takeCompressedRegionScreenshotDeprecated(sandboxId, height, width, y, x, xNightonaOrganizationID, scale, quality, format, showCursor);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Take compressed screenshot
     *
     * Take a compressed screenshot with format, quality, and scale options
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void takeCompressedScreenshotDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        BigDecimal scale = null;
        BigDecimal quality = null;
        String format = null;
        Boolean showCursor = null;
        CompressedScreenshotResponse response = api.takeCompressedScreenshotDeprecated(sandboxId, xNightonaOrganizationID, scale, quality, format, showCursor);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Take region screenshot
     *
     * Take a screenshot of a specific region
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void takeRegionScreenshotDeprecatedTest() throws ApiException {
        String sandboxId = null;
        BigDecimal height = null;
        BigDecimal width = null;
        BigDecimal y = null;
        BigDecimal x = null;
        String xNightonaOrganizationID = null;
        Boolean showCursor = null;
        RegionScreenshotResponse response = api.takeRegionScreenshotDeprecated(sandboxId, height, width, y, x, xNightonaOrganizationID, showCursor);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Take screenshot
     *
     * Take a screenshot of the entire screen
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void takeScreenshotDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        Boolean showCursor = null;
        ScreenshotResponse response = api.takeScreenshotDeprecated(sandboxId, xNightonaOrganizationID, showCursor);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Type text
     *
     * Type text using keyboard
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void typeTextDeprecatedTest() throws ApiException {
        String sandboxId = null;
        KeyboardTypeRequest keyboardTypeRequest = null;
        String xNightonaOrganizationID = null;
        api.typeTextDeprecated(sandboxId, keyboardTypeRequest, xNightonaOrganizationID);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Upload file
     *
     * Upload file inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadFileDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String path = null;
        String xNightonaOrganizationID = null;
        File _file = null;
        api.uploadFileDeprecated(sandboxId, path, xNightonaOrganizationID, _file);
        // TODO: test validations
    }

    /**
     * [DEPRECATED] Upload multiple files
     *
     * Upload multiple files inside sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadFilesDeprecatedTest() throws ApiException {
        String sandboxId = null;
        String xNightonaOrganizationID = null;
        api.uploadFilesDeprecated(sandboxId, xNightonaOrganizationID);
        // TODO: test validations
    }

}
