#!/bin/bash
set -e

# Stop the service if it's running
if systemctl is-active --quiet nightona-runner.service; then
    systemctl stop nightona-runner.service
fi

# Disable the service
if systemctl is-enabled --quiet nightona-runner.service; then
    systemctl disable nightona-runner.service
fi

exit 0
