# coding: utf-8

from __future__ import annotations

# flake8: noqa

"""
    Nightona Toolbox API

    Nightona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Nightona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Nightona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

__version__ = "0.0.0-dev"

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # import apis into sdk package
    from nightona_toolbox_api_client.api.computer_use_api import ComputerUseApi
    from nightona_toolbox_api_client.api.file_system_api import FileSystemApi
    from nightona_toolbox_api_client.api.git_api import GitApi
    from nightona_toolbox_api_client.api.info_api import InfoApi
    from nightona_toolbox_api_client.api.interpreter_api import InterpreterApi
    from nightona_toolbox_api_client.api.lsp_api import LspApi
    from nightona_toolbox_api_client.api.port_api import PortApi
    from nightona_toolbox_api_client.api.process_api import ProcessApi
    from nightona_toolbox_api_client.api.server_api import ServerApi
    # import ApiClient
    from nightona_toolbox_api_client.api_response import ApiResponse
    from nightona_toolbox_api_client.api_client import ApiClient
    from nightona_toolbox_api_client.configuration import Configuration
    from nightona_toolbox_api_client.exceptions import OpenApiException
    from nightona_toolbox_api_client.exceptions import ApiTypeError
    from nightona_toolbox_api_client.exceptions import ApiValueError
    from nightona_toolbox_api_client.exceptions import ApiKeyError
    from nightona_toolbox_api_client.exceptions import ApiAttributeError
    from nightona_toolbox_api_client.exceptions import ApiException

    # import models into sdk package
    from nightona_toolbox_api_client.models.accessibility_bounds import AccessibilityBounds
    from nightona_toolbox_api_client.models.accessibility_invoke_request import AccessibilityInvokeRequest
    from nightona_toolbox_api_client.models.accessibility_node_request import AccessibilityNodeRequest
    from nightona_toolbox_api_client.models.accessibility_nodes_response import AccessibilityNodesResponse
    from nightona_toolbox_api_client.models.accessibility_set_value_request import AccessibilitySetValueRequest
    from nightona_toolbox_api_client.models.accessibility_tree_response import AccessibilityTreeResponse
    from nightona_toolbox_api_client.models.chart import Chart
    from nightona_toolbox_api_client.models.chart_element import ChartElement
    from nightona_toolbox_api_client.models.code_run_artifacts import CodeRunArtifacts
    from nightona_toolbox_api_client.models.code_run_request import CodeRunRequest
    from nightona_toolbox_api_client.models.code_run_response import CodeRunResponse
    from nightona_toolbox_api_client.models.command import Command
    from nightona_toolbox_api_client.models.completion_context import CompletionContext
    from nightona_toolbox_api_client.models.completion_item import CompletionItem
    from nightona_toolbox_api_client.models.completion_list import CompletionList
    from nightona_toolbox_api_client.models.computer_use_accessibility_node import ComputerUseAccessibilityNode
    from nightona_toolbox_api_client.models.computer_use_start_response import ComputerUseStartResponse
    from nightona_toolbox_api_client.models.computer_use_status_response import ComputerUseStatusResponse
    from nightona_toolbox_api_client.models.computer_use_stop_response import ComputerUseStopResponse
    from nightona_toolbox_api_client.models.create_context_request import CreateContextRequest
    from nightona_toolbox_api_client.models.create_session_request import CreateSessionRequest
    from nightona_toolbox_api_client.models.display_info import DisplayInfo
    from nightona_toolbox_api_client.models.display_info_response import DisplayInfoResponse
    from nightona_toolbox_api_client.models.execute_request import ExecuteRequest
    from nightona_toolbox_api_client.models.execute_response import ExecuteResponse
    from nightona_toolbox_api_client.models.file_info import FileInfo
    from nightona_toolbox_api_client.models.file_status import FileStatus
    from nightona_toolbox_api_client.models.files_download_request import FilesDownloadRequest
    from nightona_toolbox_api_client.models.find_accessibility_nodes_request import FindAccessibilityNodesRequest
    from nightona_toolbox_api_client.models.git_add_request import GitAddRequest
    from nightona_toolbox_api_client.models.git_branch_request import GitBranchRequest
    from nightona_toolbox_api_client.models.git_checkout_request import GitCheckoutRequest
    from nightona_toolbox_api_client.models.git_clone_request import GitCloneRequest
    from nightona_toolbox_api_client.models.git_commit_info import GitCommitInfo
    from nightona_toolbox_api_client.models.git_commit_request import GitCommitRequest
    from nightona_toolbox_api_client.models.git_commit_response import GitCommitResponse
    from nightona_toolbox_api_client.models.git_delete_branch_request import GitDeleteBranchRequest
    from nightona_toolbox_api_client.models.git_repo_request import GitRepoRequest
    from nightona_toolbox_api_client.models.git_status import GitStatus
    from nightona_toolbox_api_client.models.initialize_request import InitializeRequest
    from nightona_toolbox_api_client.models.interpreter_context import InterpreterContext
    from nightona_toolbox_api_client.models.is_port_in_use_response import IsPortInUseResponse
    from nightona_toolbox_api_client.models.keyboard_hotkey_request import KeyboardHotkeyRequest
    from nightona_toolbox_api_client.models.keyboard_press_request import KeyboardPressRequest
    from nightona_toolbox_api_client.models.keyboard_type_request import KeyboardTypeRequest
    from nightona_toolbox_api_client.models.list_branch_response import ListBranchResponse
    from nightona_toolbox_api_client.models.list_contexts_response import ListContextsResponse
    from nightona_toolbox_api_client.models.list_recordings_response import ListRecordingsResponse
    from nightona_toolbox_api_client.models.lsp_completion_params import LspCompletionParams
    from nightona_toolbox_api_client.models.lsp_document_request import LspDocumentRequest
    from nightona_toolbox_api_client.models.lsp_location import LspLocation
    from nightona_toolbox_api_client.models.lsp_position import LspPosition
    from nightona_toolbox_api_client.models.lsp_range import LspRange
    from nightona_toolbox_api_client.models.lsp_server_request import LspServerRequest
    from nightona_toolbox_api_client.models.lsp_symbol import LspSymbol
    from nightona_toolbox_api_client.models.match import Match
    from nightona_toolbox_api_client.models.mouse_click_request import MouseClickRequest
    from nightona_toolbox_api_client.models.mouse_click_response import MouseClickResponse
    from nightona_toolbox_api_client.models.mouse_drag_request import MouseDragRequest
    from nightona_toolbox_api_client.models.mouse_drag_response import MouseDragResponse
    from nightona_toolbox_api_client.models.mouse_move_request import MouseMoveRequest
    from nightona_toolbox_api_client.models.mouse_position_response import MousePositionResponse
    from nightona_toolbox_api_client.models.mouse_scroll_request import MouseScrollRequest
    from nightona_toolbox_api_client.models.port_list import PortList
    from nightona_toolbox_api_client.models.position import Position
    from nightona_toolbox_api_client.models.process_errors_response import ProcessErrorsResponse
    from nightona_toolbox_api_client.models.process_logs_response import ProcessLogsResponse
    from nightona_toolbox_api_client.models.process_restart_response import ProcessRestartResponse
    from nightona_toolbox_api_client.models.process_status import ProcessStatus
    from nightona_toolbox_api_client.models.process_status_response import ProcessStatusResponse
    from nightona_toolbox_api_client.models.pty_create_request import PtyCreateRequest
    from nightona_toolbox_api_client.models.pty_create_response import PtyCreateResponse
    from nightona_toolbox_api_client.models.pty_list_response import PtyListResponse
    from nightona_toolbox_api_client.models.pty_resize_request import PtyResizeRequest
    from nightona_toolbox_api_client.models.pty_session_info import PtySessionInfo
    from nightona_toolbox_api_client.models.recording import Recording
    from nightona_toolbox_api_client.models.replace_request import ReplaceRequest
    from nightona_toolbox_api_client.models.replace_result import ReplaceResult
    from nightona_toolbox_api_client.models.screenshot_response import ScreenshotResponse
    from nightona_toolbox_api_client.models.scroll_response import ScrollResponse
    from nightona_toolbox_api_client.models.search_files_response import SearchFilesResponse
    from nightona_toolbox_api_client.models.session import Session
    from nightona_toolbox_api_client.models.session_command_logs_response import SessionCommandLogsResponse
    from nightona_toolbox_api_client.models.session_execute_request import SessionExecuteRequest
    from nightona_toolbox_api_client.models.session_execute_response import SessionExecuteResponse
    from nightona_toolbox_api_client.models.session_send_input_request import SessionSendInputRequest
    from nightona_toolbox_api_client.models.start_recording_request import StartRecordingRequest
    from nightona_toolbox_api_client.models.status import Status
    from nightona_toolbox_api_client.models.stop_recording_request import StopRecordingRequest
    from nightona_toolbox_api_client.models.user_home_dir_response import UserHomeDirResponse
    from nightona_toolbox_api_client.models.window_info import WindowInfo
    from nightona_toolbox_api_client.models.windows_response import WindowsResponse
    from nightona_toolbox_api_client.models.work_dir_response import WorkDirResponse

_DYNAMIC_IMPORTS: dict[str, str] = {
    # apis
    "ComputerUseApi": "nightona_toolbox_api_client.api.computer_use_api",
    "FileSystemApi": "nightona_toolbox_api_client.api.file_system_api",
    "GitApi": "nightona_toolbox_api_client.api.git_api",
    "InfoApi": "nightona_toolbox_api_client.api.info_api",
    "InterpreterApi": "nightona_toolbox_api_client.api.interpreter_api",
    "LspApi": "nightona_toolbox_api_client.api.lsp_api",
    "PortApi": "nightona_toolbox_api_client.api.port_api",
    "ProcessApi": "nightona_toolbox_api_client.api.process_api",
    "ServerApi": "nightona_toolbox_api_client.api.server_api",
    # ApiClient
    "ApiResponse": "nightona_toolbox_api_client.api_response",
    "ApiClient": "nightona_toolbox_api_client.api_client",
    "Configuration": "nightona_toolbox_api_client.configuration",
    "OpenApiException": "nightona_toolbox_api_client.exceptions",
    "ApiTypeError": "nightona_toolbox_api_client.exceptions",
    "ApiValueError": "nightona_toolbox_api_client.exceptions",
    "ApiKeyError": "nightona_toolbox_api_client.exceptions",
    "ApiAttributeError": "nightona_toolbox_api_client.exceptions",
    "ApiException": "nightona_toolbox_api_client.exceptions",
    # models
    "AccessibilityBounds": "nightona_toolbox_api_client.models.accessibility_bounds",
    "AccessibilityInvokeRequest": "nightona_toolbox_api_client.models.accessibility_invoke_request",
    "AccessibilityNodeRequest": "nightona_toolbox_api_client.models.accessibility_node_request",
    "AccessibilityNodesResponse": "nightona_toolbox_api_client.models.accessibility_nodes_response",
    "AccessibilitySetValueRequest": "nightona_toolbox_api_client.models.accessibility_set_value_request",
    "AccessibilityTreeResponse": "nightona_toolbox_api_client.models.accessibility_tree_response",
    "Chart": "nightona_toolbox_api_client.models.chart",
    "ChartElement": "nightona_toolbox_api_client.models.chart_element",
    "CodeRunArtifacts": "nightona_toolbox_api_client.models.code_run_artifacts",
    "CodeRunRequest": "nightona_toolbox_api_client.models.code_run_request",
    "CodeRunResponse": "nightona_toolbox_api_client.models.code_run_response",
    "Command": "nightona_toolbox_api_client.models.command",
    "CompletionContext": "nightona_toolbox_api_client.models.completion_context",
    "CompletionItem": "nightona_toolbox_api_client.models.completion_item",
    "CompletionList": "nightona_toolbox_api_client.models.completion_list",
    "ComputerUseAccessibilityNode": "nightona_toolbox_api_client.models.computer_use_accessibility_node",
    "ComputerUseStartResponse": "nightona_toolbox_api_client.models.computer_use_start_response",
    "ComputerUseStatusResponse": "nightona_toolbox_api_client.models.computer_use_status_response",
    "ComputerUseStopResponse": "nightona_toolbox_api_client.models.computer_use_stop_response",
    "CreateContextRequest": "nightona_toolbox_api_client.models.create_context_request",
    "CreateSessionRequest": "nightona_toolbox_api_client.models.create_session_request",
    "DisplayInfo": "nightona_toolbox_api_client.models.display_info",
    "DisplayInfoResponse": "nightona_toolbox_api_client.models.display_info_response",
    "ExecuteRequest": "nightona_toolbox_api_client.models.execute_request",
    "ExecuteResponse": "nightona_toolbox_api_client.models.execute_response",
    "FileInfo": "nightona_toolbox_api_client.models.file_info",
    "FileStatus": "nightona_toolbox_api_client.models.file_status",
    "FilesDownloadRequest": "nightona_toolbox_api_client.models.files_download_request",
    "FindAccessibilityNodesRequest": "nightona_toolbox_api_client.models.find_accessibility_nodes_request",
    "GitAddRequest": "nightona_toolbox_api_client.models.git_add_request",
    "GitBranchRequest": "nightona_toolbox_api_client.models.git_branch_request",
    "GitCheckoutRequest": "nightona_toolbox_api_client.models.git_checkout_request",
    "GitCloneRequest": "nightona_toolbox_api_client.models.git_clone_request",
    "GitCommitInfo": "nightona_toolbox_api_client.models.git_commit_info",
    "GitCommitRequest": "nightona_toolbox_api_client.models.git_commit_request",
    "GitCommitResponse": "nightona_toolbox_api_client.models.git_commit_response",
    "GitDeleteBranchRequest": "nightona_toolbox_api_client.models.git_delete_branch_request",
    "GitRepoRequest": "nightona_toolbox_api_client.models.git_repo_request",
    "GitStatus": "nightona_toolbox_api_client.models.git_status",
    "InitializeRequest": "nightona_toolbox_api_client.models.initialize_request",
    "InterpreterContext": "nightona_toolbox_api_client.models.interpreter_context",
    "IsPortInUseResponse": "nightona_toolbox_api_client.models.is_port_in_use_response",
    "KeyboardHotkeyRequest": "nightona_toolbox_api_client.models.keyboard_hotkey_request",
    "KeyboardPressRequest": "nightona_toolbox_api_client.models.keyboard_press_request",
    "KeyboardTypeRequest": "nightona_toolbox_api_client.models.keyboard_type_request",
    "ListBranchResponse": "nightona_toolbox_api_client.models.list_branch_response",
    "ListContextsResponse": "nightona_toolbox_api_client.models.list_contexts_response",
    "ListRecordingsResponse": "nightona_toolbox_api_client.models.list_recordings_response",
    "LspCompletionParams": "nightona_toolbox_api_client.models.lsp_completion_params",
    "LspDocumentRequest": "nightona_toolbox_api_client.models.lsp_document_request",
    "LspLocation": "nightona_toolbox_api_client.models.lsp_location",
    "LspPosition": "nightona_toolbox_api_client.models.lsp_position",
    "LspRange": "nightona_toolbox_api_client.models.lsp_range",
    "LspServerRequest": "nightona_toolbox_api_client.models.lsp_server_request",
    "LspSymbol": "nightona_toolbox_api_client.models.lsp_symbol",
    "Match": "nightona_toolbox_api_client.models.match",
    "MouseClickRequest": "nightona_toolbox_api_client.models.mouse_click_request",
    "MouseClickResponse": "nightona_toolbox_api_client.models.mouse_click_response",
    "MouseDragRequest": "nightona_toolbox_api_client.models.mouse_drag_request",
    "MouseDragResponse": "nightona_toolbox_api_client.models.mouse_drag_response",
    "MouseMoveRequest": "nightona_toolbox_api_client.models.mouse_move_request",
    "MousePositionResponse": "nightona_toolbox_api_client.models.mouse_position_response",
    "MouseScrollRequest": "nightona_toolbox_api_client.models.mouse_scroll_request",
    "PortList": "nightona_toolbox_api_client.models.port_list",
    "Position": "nightona_toolbox_api_client.models.position",
    "ProcessErrorsResponse": "nightona_toolbox_api_client.models.process_errors_response",
    "ProcessLogsResponse": "nightona_toolbox_api_client.models.process_logs_response",
    "ProcessRestartResponse": "nightona_toolbox_api_client.models.process_restart_response",
    "ProcessStatus": "nightona_toolbox_api_client.models.process_status",
    "ProcessStatusResponse": "nightona_toolbox_api_client.models.process_status_response",
    "PtyCreateRequest": "nightona_toolbox_api_client.models.pty_create_request",
    "PtyCreateResponse": "nightona_toolbox_api_client.models.pty_create_response",
    "PtyListResponse": "nightona_toolbox_api_client.models.pty_list_response",
    "PtyResizeRequest": "nightona_toolbox_api_client.models.pty_resize_request",
    "PtySessionInfo": "nightona_toolbox_api_client.models.pty_session_info",
    "Recording": "nightona_toolbox_api_client.models.recording",
    "ReplaceRequest": "nightona_toolbox_api_client.models.replace_request",
    "ReplaceResult": "nightona_toolbox_api_client.models.replace_result",
    "ScreenshotResponse": "nightona_toolbox_api_client.models.screenshot_response",
    "ScrollResponse": "nightona_toolbox_api_client.models.scroll_response",
    "SearchFilesResponse": "nightona_toolbox_api_client.models.search_files_response",
    "Session": "nightona_toolbox_api_client.models.session",
    "SessionCommandLogsResponse": "nightona_toolbox_api_client.models.session_command_logs_response",
    "SessionExecuteRequest": "nightona_toolbox_api_client.models.session_execute_request",
    "SessionExecuteResponse": "nightona_toolbox_api_client.models.session_execute_response",
    "SessionSendInputRequest": "nightona_toolbox_api_client.models.session_send_input_request",
    "StartRecordingRequest": "nightona_toolbox_api_client.models.start_recording_request",
    "Status": "nightona_toolbox_api_client.models.status",
    "StopRecordingRequest": "nightona_toolbox_api_client.models.stop_recording_request",
    "UserHomeDirResponse": "nightona_toolbox_api_client.models.user_home_dir_response",
    "WindowInfo": "nightona_toolbox_api_client.models.window_info",
    "WindowsResponse": "nightona_toolbox_api_client.models.windows_response",
    "WorkDirResponse": "nightona_toolbox_api_client.models.work_dir_response",
}


def __getattr__(attr_name: str) -> object:
    module_path = _DYNAMIC_IMPORTS.get(attr_name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {attr_name!r}")
    mod = importlib.import_module(module_path)
    value = getattr(mod, attr_name)
    globals()[attr_name] = value
    return value


def __dir__() -> list[str]:
    return list(_DYNAMIC_IMPORTS.keys())


# --- Static __all__ generated by Mustache ---
__all__ = [
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ComputerUseApi",
    "FileSystemApi",
    "GitApi",
    "InfoApi",
    "InterpreterApi",
    "LspApi",
    "PortApi",
    "ProcessApi",
    "ServerApi",
    "AccessibilityBounds",
    "AccessibilityInvokeRequest",
    "AccessibilityNodeRequest",
    "AccessibilityNodesResponse",
    "AccessibilitySetValueRequest",
    "AccessibilityTreeResponse",
    "Chart",
    "ChartElement",
    "CodeRunArtifacts",
    "CodeRunRequest",
    "CodeRunResponse",
    "Command",
    "CompletionContext",
    "CompletionItem",
    "CompletionList",
    "ComputerUseAccessibilityNode",
    "ComputerUseStartResponse",
    "ComputerUseStatusResponse",
    "ComputerUseStopResponse",
    "CreateContextRequest",
    "CreateSessionRequest",
    "DisplayInfo",
    "DisplayInfoResponse",
    "ExecuteRequest",
    "ExecuteResponse",
    "FileInfo",
    "FileStatus",
    "FilesDownloadRequest",
    "FindAccessibilityNodesRequest",
    "GitAddRequest",
    "GitBranchRequest",
    "GitCheckoutRequest",
    "GitCloneRequest",
    "GitCommitInfo",
    "GitCommitRequest",
    "GitCommitResponse",
    "GitDeleteBranchRequest",
    "GitRepoRequest",
    "GitStatus",
    "InitializeRequest",
    "InterpreterContext",
    "IsPortInUseResponse",
    "KeyboardHotkeyRequest",
    "KeyboardPressRequest",
    "KeyboardTypeRequest",
    "ListBranchResponse",
    "ListContextsResponse",
    "ListRecordingsResponse",
    "LspCompletionParams",
    "LspDocumentRequest",
    "LspLocation",
    "LspPosition",
    "LspRange",
    "LspServerRequest",
    "LspSymbol",
    "Match",
    "MouseClickRequest",
    "MouseClickResponse",
    "MouseDragRequest",
    "MouseDragResponse",
    "MouseMoveRequest",
    "MousePositionResponse",
    "MouseScrollRequest",
    "PortList",
    "Position",
    "ProcessErrorsResponse",
    "ProcessLogsResponse",
    "ProcessRestartResponse",
    "ProcessStatus",
    "ProcessStatusResponse",
    "PtyCreateRequest",
    "PtyCreateResponse",
    "PtyListResponse",
    "PtyResizeRequest",
    "PtySessionInfo",
    "Recording",
    "ReplaceRequest",
    "ReplaceResult",
    "ScreenshotResponse",
    "ScrollResponse",
    "SearchFilesResponse",
    "Session",
    "SessionCommandLogsResponse",
    "SessionExecuteRequest",
    "SessionExecuteResponse",
    "SessionSendInputRequest",
    "StartRecordingRequest",
    "Status",
    "StopRecordingRequest",
    "UserHomeDirResponse",
    "WindowInfo",
    "WindowsResponse",
    "WorkDirResponse",

]