"""
    Nightona

    Nightona AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: amaraaamka0404@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "nightona_api_client"
VERSION = "0.0.0-dev"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Nightona",
    author="Nightona contributors",
    author_email="amaraaamka0404@gmail.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Nightona"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache-2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    Nightona AI platform API Docs
    """,  # noqa: E501
    package_data={"nightona_api_client": ["py.typed"]},
)
