=begin
#Nightona

#Nightona AI platform API Docs

The version of the OpenAPI document: 1.0
Contact: amaraaamka0404@gmail.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

module NightonaApiClient
  VERSION = '0.0.0.pre.dev'
end
