/* tslint:disable */
/* eslint-disable */
/**
 * Nightona Toolbox API
 * Nightona Toolbox API. The base URL comes from the sandbox\'s `toolboxProxyUrl` field (returned in sandbox DTO by the main Nightona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Nightona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ExecuteRequest {
    'command': string;
    /**
     * Current working directory
     */
    'cwd'?: string;
    /**
     * Environment variables to set for the command
     */
    'envs'?: { [key: string]: string; };
    /**
     * Timeout in seconds, defaults to 10 seconds
     */
    'timeout'?: number;
}

