/* tslint:disable */
/* eslint-disable */
/**
 * Nightona
 * Nightona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: amaraaamka0404@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { StorageAccessDto } from '../models';
/**
 * ObjectStorageApi - axios parameter creator
 */
export const ObjectStorageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get temporary storage access for pushing objects
         * @param {string} [xNightonaOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPushAccess: async (xNightonaOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/object-storage/push-access`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xNightonaOrganizationID != null) {
                localVarHeaderParameter['X-Nightona-Organization-ID'] = String(xNightonaOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ObjectStorageApi - functional programming interface
 */
export const ObjectStorageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ObjectStorageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get temporary storage access for pushing objects
         * @param {string} [xNightonaOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPushAccess(xNightonaOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StorageAccessDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPushAccess(xNightonaOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObjectStorageApi.getPushAccess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ObjectStorageApi - factory interface
 */
export const ObjectStorageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ObjectStorageApiFp(configuration)
    return {
        /**
         * 
         * @summary Get temporary storage access for pushing objects
         * @param {string} [xNightonaOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPushAccess(xNightonaOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<StorageAccessDto> {
            return localVarFp.getPushAccess(xNightonaOrganizationID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ObjectStorageApi - object-oriented interface
 */
export class ObjectStorageApi extends BaseAPI {
    /**
     * 
     * @summary Get temporary storage access for pushing objects
     * @param {string} [xNightonaOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPushAccess(xNightonaOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return ObjectStorageApiFp(this.configuration).getPushAccess(xNightonaOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }
}

